base_url = "https://deadkai.github.io"
theme = "Seje2"
compile_sass = true
default_language = "en"
generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]
build_search_index = false

[markdown]
highlight_code = true

[extra]
seje_show_summary_only = false
seje_darkmode = "auto"
seje_menu_links = [
    {url = "$BASE_URL/", name = "home"},
    {url = "$BASE_URL/archives", name = "archives"},
    {url = "$BASE_URL/about", name = "about"},
    {url = "$BASE_URL/atom.xml", name = "rss"},
]

[languages.en.translations]
title = "title"
home = "home"
archives = "archives"
about = "about"
rss = "rss"
more = "more"
olderArticle = "olderArticle"
newer = "newer"
older = "older"
loading = "loading"

